name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

env:
  DRIVER_KIND: remote

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      browserless:
        image: browserless/chrome:latest
        env:
          ALLOW_FILE_PROTOCOL: "true"
        ports:
          - 3000:3000

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/test.txt
    - name: Type checking
      run: |
        mypy .
    - name: Pylinting
      run: |
        pylint *.py
    - name: Tests
      run: |
        mkdir reports
        ./upload_test_files.sh
        pytest page_element --html=reports/report.html --self-contained-html
    - name: Archive test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: reports
